### ISSUE TITLE
いちいち `npm run rsync` しないといけないのがめんどくさい

### ISSUE THREAD

**Issue by miya0001** [geolonia/geo-scratch#1]
* scratch のエクステンションは、`scratch-vm` と `scratch-gui` の2つのモジュール内のファイルを修正する必要がある。
  * `scratch-vm` は、Scratch で作成したアプリを動作させるためのバーチャルマシンのような存在かつエクステンション本体の JS はこのモジュール内のファイルを修正する必要がある。
  * `scratch-gui` は、Scratch 本体。Scratch の GUI を起動するには `scratch-gui` が必要。
  * この `geo-scratch` は、`scratch-gui` のフォーク

などなどの事情により、ファイルを修正するたびに rsync しているのでなんとかしたい。

**Comment by keichan34** [comment]
`nodemon` を devDependencies に入れて scripts の `run` を `nodemon npm run rsync` とかで行けるかな。。
